spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.36.133
    port: 5672
    username: admin
    password: admin
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
#需要开启ribbon重试，默认不开启
zuul:
  retryable: true
#item-service  item-service默认配置
#zuul:
  #routes:
    #item-service: /item-service/**
    #user-service: /user-service/**
    #order-service: /order-service/**
#有默认可不配置,重试
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
#熔断
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
#enable包含了熔断
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream